name: keymap

on: # yamllint disable-line rule:truthy
  push: null

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: qmkfm/qmk_cli

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup QMK Firmware
      run: |
        git submodule update --init
        cd qmk_firmware
        make git-submodule
        qmk setup

    - name: Copy custom keymap definition
      run: |
        cp -rp $GITHUB_WORKSPACE/crkbd3/keymap $GITHUB_WORKSPACE/qmk_firmware/keyboards/crkbd/keymaps/nobleascent

    - name: Build custom firmware
      shell: bash
      run: |
        cd qmk_firmware
        timeout 10s qmk compile -kb crkbd -km nobleascent || [[ $? -eq 124 ]]
        qmk c2json -kb crkbd -km nobleascent -o nobleascent.json $(pwd)/keyboards/crkbd/keymaps/nobleascent/keymap.c
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Hex files
        path: qmk_firmware/*.hex
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          qmk_firmware/crkbd_rev1_nobleascent.hex
          qmk_firmware/nobleascent.json